import { KeyEventType } from "./KeyEventType.js";
/**
 * KeyEvent
 */
export declare class KeyEvent {
  /**
   * This class should not be instantiated by users of LuciadRIA.
   */
  private constructor();
  /**
   * The raw dom event generated by the browser.
   */
  get domEvent(): KeyboardEvent | null;
  set domEvent(value: KeyboardEvent | null);
  /**
   * The input modality type. Always 'keyboard'.
   */
  get inputType(): string;
  set inputType(value: string);
  /**
   * The event type. One of the constants from {@link KeyEventType}.
   */
  get type(): KeyEventType;
  set type(value: KeyEventType);
}